### PR TITLE
Fix for New Adventure "Read Aloud" Formatting

### LINKED ISSUE #996: Mine of Phandelver DNDbeyond sourcebook descriptive blocks not longer able to "display in vtt"
**Describe the bug**
Mine of Phandelver DNDbeyond sourcebook descriptive blocks not longer able to "display in vtt"

**To Reproduce**
on any computer with dndbeyond sourcebook mine of phandelver sourcebook bought search for a descriptive text block, and it is not able to display in vvt

**Expected behavior**
red button should be there, any other sourcebook campaign still works

**Screenshots**
image

**Browser Info (please complete the following information):**
chrome OS

**Additional context**
any other sourcebook works, seems layout mine of phandelver is changed?

### PR DESCRIPTION
**Pull request by Aeristoka**
Particularly in Lost Mine of Phandelver (for now)
Fixes #996

### CODE REVIEW

File: src/dndbeyond/content-scripts/source.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ function documentLoaded(settings) {
             injectDiceToRolls(".primary-content", character, (node) => {
                 return nearestHeading(node, source_name);
             });
-            const read_aloud = $(".read-aloud-text,.adventure-read-aloud-text");
+            const read_aloud = $(".read-aloud-text,.adventure-read-aloud-text,.text--quote-box");
```
Comment (kakaroto) [inline src/dndbeyond/content-scripts/source.js:45]: I'm not sure if I'd put `aside.text--quote-box` to be more specific, or if I'd put it the way you did so it's more inclusive (in case they use something other than `aside` somewhere else, and "quote-box" seems to be a descriptive enough class...) 🤔

Comment (Aeristoka) [reply src/dndbeyond/content-scripts/source.js:45]: Dude, who knows, they might change every single thing tomorrow again, the way they're going...

Comment (kakaroto) [reply src/dndbeyond/content-scripts/source.js:45]: lol, very true! 😁 
Anyways, I thought on it for a bit and I think it's better without the `aside` anyway, so will merge it now, thanks!
