### PR TITLE
Fix for Chaos Bolt using new resolveRolls

### LINKED ISSUE #344: Chaos bolt
chaos bolt has a box asking for a damage type before the roll My assumption is it's picking up the same thing chromatic Orb does but that conflicts with the special case stuff you've had to do for Chaos bolt in the past because the drop down is empty

image

### PR DESCRIPTION
**Pull request by Aeristoka**
Moves the processing for Chaos Bolt after resolveRolls
Allows Chaos Bolt to process the roll results properly

Fixes #344

### CODE REVIEW

File: src/common/roll_renderer.js [hunk 1]
```diff
@@ -595,6 +595,9 @@ class Beyond20RollRenderer {
                 }
             }
 
+            await this._roller.resolveRolls(request.name, all_rolls)
+            
+            //Moved after the new resolveRolls so it can access the roll results
```
Comment (kakaroto) [inline src/common/roll_renderer.js:600]: This comment is not needed, because it explains what this specific commit does, not the code. So reading the code back in a year, we see "moved after... " and we wonder "why is this saying moved?" 
A comment like "Handle Chaos Bolt after the rolls are resolved" would be nicer. Also, space after `//`  :p
